// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: server_streaming/serverstreamingpb/server_streaming.proto

package serverstreamingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Damage uint32 `protobuf:"varint,1,opt,name=damage,proto3" json:"damage,omitempty"`
}

func (x *Attack) Reset() {
	*x = Attack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attack) ProtoMessage() {}

func (x *Attack) ProtoReflect() protoreflect.Message {
	mi := &file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attack.ProtoReflect.Descriptor instead.
func (*Attack) Descriptor() ([]byte, []int) {
	return file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *Attack) GetDamage() uint32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type Boss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Health int32  `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
}

func (x *Boss) Reset() {
	*x = Boss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Boss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boss) ProtoMessage() {}

func (x *Boss) ProtoReflect() protoreflect.Message {
	mi := &file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boss.ProtoReflect.Descriptor instead.
func (*Boss) Descriptor() ([]byte, []int) {
	return file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *Boss) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Boss) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Health int32  `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

type AttackBossRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attack *Attack `protobuf:"bytes,1,opt,name=attack,proto3" json:"attack,omitempty"`
	Boss   *Boss   `protobuf:"bytes,2,opt,name=boss,proto3" json:"boss,omitempty"`
}

func (x *AttackBossRequest) Reset() {
	*x = AttackBossRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttackBossRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackBossRequest) ProtoMessage() {}

func (x *AttackBossRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackBossRequest.ProtoReflect.Descriptor instead.
func (*AttackBossRequest) Descriptor() ([]byte, []int) {
	return file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *AttackBossRequest) GetAttack() *Attack {
	if x != nil {
		return x.Attack
	}
	return nil
}

func (x *AttackBossRequest) GetBoss() *Boss {
	if x != nil {
		return x.Boss
	}
	return nil
}

type AttackBossResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boss   *Boss   `protobuf:"bytes,1,opt,name=boss,proto3" json:"boss,omitempty"`
	Player *Player `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *AttackBossResponse) Reset() {
	*x = AttackBossResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttackBossResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackBossResponse) ProtoMessage() {}

func (x *AttackBossResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackBossResponse.ProtoReflect.Descriptor instead.
func (*AttackBossResponse) Descriptor() ([]byte, []int) {
	return file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *AttackBossResponse) GetBoss() *Boss {
	if x != nil {
		return x.Boss
	}
	return nil
}

func (x *AttackBossResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

var File_server_streaming_serverstreamingpb_server_streaming_proto protoreflect.FileDescriptor

var file_server_streaming_serverstreamingpb_server_streaming_proto_rawDesc = []byte{
	0x0a, 0x39, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x6e, 0x61,
	0x72, 0x79, 0x22, 0x20, 0x0a, 0x06, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x64, 0x61,
	0x6d, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x04, 0x42, 0x6f, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x22, 0x34, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x5b, 0x0a, 0x11, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x25, 0x0a, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x06,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x1f, 0x0a, 0x04, 0x62, 0x6f, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x42, 0x6f, 0x73,
	0x73, 0x52, 0x04, 0x62, 0x6f, 0x73, 0x73, 0x22, 0x5c, 0x0a, 0x12, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x6b, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x04, 0x62, 0x6f, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x6e,
	0x61, 0x72, 0x79, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x04, 0x62, 0x6f, 0x73, 0x73, 0x12, 0x25,
	0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x5f, 0x0a, 0x16, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x45, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x42, 0x6f, 0x73, 0x73, 0x12, 0x18, 0x2e,
	0x75, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x42, 0x6f, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x2e,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x26, 0x5a, 0x24, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescOnce sync.Once
	file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescData = file_server_streaming_serverstreamingpb_server_streaming_proto_rawDesc
)

func file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescGZIP() []byte {
	file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescOnce.Do(func() {
		file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescData)
	})
	return file_server_streaming_serverstreamingpb_server_streaming_proto_rawDescData
}

var file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_server_streaming_serverstreamingpb_server_streaming_proto_goTypes = []interface{}{
	(*Attack)(nil),             // 0: unary.Attack
	(*Boss)(nil),               // 1: unary.Boss
	(*Player)(nil),             // 2: unary.Player
	(*AttackBossRequest)(nil),  // 3: unary.AttackBossRequest
	(*AttackBossResponse)(nil), // 4: unary.AttackBossResponse
}
var file_server_streaming_serverstreamingpb_server_streaming_proto_depIdxs = []int32{
	0, // 0: unary.AttackBossRequest.attack:type_name -> unary.Attack
	1, // 1: unary.AttackBossRequest.boss:type_name -> unary.Boss
	1, // 2: unary.AttackBossResponse.boss:type_name -> unary.Boss
	2, // 3: unary.AttackBossResponse.player:type_name -> unary.Player
	3, // 4: unary.ServerStreamingService.AttackBoss:input_type -> unary.AttackBossRequest
	4, // 5: unary.ServerStreamingService.AttackBoss:output_type -> unary.AttackBossResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_server_streaming_serverstreamingpb_server_streaming_proto_init() }
func file_server_streaming_serverstreamingpb_server_streaming_proto_init() {
	if File_server_streaming_serverstreamingpb_server_streaming_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Boss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttackBossRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttackBossResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_streaming_serverstreamingpb_server_streaming_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_streaming_serverstreamingpb_server_streaming_proto_goTypes,
		DependencyIndexes: file_server_streaming_serverstreamingpb_server_streaming_proto_depIdxs,
		MessageInfos:      file_server_streaming_serverstreamingpb_server_streaming_proto_msgTypes,
	}.Build()
	File_server_streaming_serverstreamingpb_server_streaming_proto = out.File
	file_server_streaming_serverstreamingpb_server_streaming_proto_rawDesc = nil
	file_server_streaming_serverstreamingpb_server_streaming_proto_goTypes = nil
	file_server_streaming_serverstreamingpb_server_streaming_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServerStreamingServiceClient is the client API for ServerStreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerStreamingServiceClient interface {
	AttackBoss(ctx context.Context, in *AttackBossRequest, opts ...grpc.CallOption) (ServerStreamingService_AttackBossClient, error)
}

type serverStreamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServerStreamingServiceClient(cc grpc.ClientConnInterface) ServerStreamingServiceClient {
	return &serverStreamingServiceClient{cc}
}

func (c *serverStreamingServiceClient) AttackBoss(ctx context.Context, in *AttackBossRequest, opts ...grpc.CallOption) (ServerStreamingService_AttackBossClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ServerStreamingService_serviceDesc.Streams[0], "/unary.ServerStreamingService/AttackBoss", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverStreamingServiceAttackBossClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServerStreamingService_AttackBossClient interface {
	Recv() (*AttackBossResponse, error)
	grpc.ClientStream
}

type serverStreamingServiceAttackBossClient struct {
	grpc.ClientStream
}

func (x *serverStreamingServiceAttackBossClient) Recv() (*AttackBossResponse, error) {
	m := new(AttackBossResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServerStreamingServiceServer is the server API for ServerStreamingService service.
type ServerStreamingServiceServer interface {
	AttackBoss(*AttackBossRequest, ServerStreamingService_AttackBossServer) error
}

// UnimplementedServerStreamingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServerStreamingServiceServer struct {
}

func (*UnimplementedServerStreamingServiceServer) AttackBoss(*AttackBossRequest, ServerStreamingService_AttackBossServer) error {
	return status.Errorf(codes.Unimplemented, "method AttackBoss not implemented")
}

func RegisterServerStreamingServiceServer(s *grpc.Server, srv ServerStreamingServiceServer) {
	s.RegisterService(&_ServerStreamingService_serviceDesc, srv)
}

func _ServerStreamingService_AttackBoss_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AttackBossRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerStreamingServiceServer).AttackBoss(m, &serverStreamingServiceAttackBossServer{stream})
}

type ServerStreamingService_AttackBossServer interface {
	Send(*AttackBossResponse) error
	grpc.ServerStream
}

type serverStreamingServiceAttackBossServer struct {
	grpc.ServerStream
}

func (x *serverStreamingServiceAttackBossServer) Send(m *AttackBossResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ServerStreamingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "unary.ServerStreamingService",
	HandlerType: (*ServerStreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttackBoss",
			Handler:       _ServerStreamingService_AttackBoss_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server_streaming/serverstreamingpb/server_streaming.proto",
}
